### ISSUE TITLE
predict得到的结果类别只有0，3，8

### ISSUE THREAD

**Issue by nmvbxcz** [ShuGuoJ/GiGCN#4]
环境完全复现，除了cuda 用的是 10.1
python predict.py --name PaviaU --block 100 --gpu 0 
预测得到的标签只有0，3，8，无法得到正确的预测结果
![image](https://user-images.githubusercontent.com/15317138/192414106-5e9d3f71-c600-4371-b227-c8dfdef4d15c.png)

**Comment by ShuGuoJ** [comment]
Please check the data and label to ensure consistency during training and testing.

**Comment by ShuGuoJ** [comment]
Please check the data and label to ensure consistency during training and testing.

**Comment by nmvbxcz** [comment]
感谢及时回复，已经调试成功，谢谢大佬开源代码
